<a href="https://colab.research.google.com/github/Wasabiie/VoNhatHao/blob/main/Lab6_Sohoa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

torch.cuda.is_available()

True

In [5]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Iris.csv")
df.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [17]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
x = df.drop(["Species"], axis=1).values
y = le.fit_transform(df["Species"].values)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state=42)

x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)
print(f"train_size : {len(y_train)}")

train_size : 120


In [18]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [21]:
import torch

# Khai báo giá trị x
x = torch.tensor(2.0, requires_grad=True)
# Tính y
y = 2 * x**4 + x**3 + 3 * x**2 + 5 * x + 1

# Tính đạo hàm
y.backward()

# In kết quả
print("Giá trị y:", y.item())
print("Đạo hàm tại x =", x.item(), "là:", x.grad.item())

Giá trị y: 63.0
Đạo hàm tại x = 2.0 là: 93.0


In [22]:
import torch
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [48]:
import sympy as sp

# Định nghĩa biến và hàm số
x = sp.symbols('x')
y = 5*x**6 + 3*x**3 + 2*x + x + 2 * x + 5*x**4 + 1

# Đơn giản hóa đa thức
y = sp.simplify(y)

# Tính đạo hàm
dy_dx = sp.diff(y, x)

# In đạo hàm
print(f"Đạo hàm của y theo x: {dy_dx}")

# Tính độ dốc tại một điểm cụ thể
a = 2
gradient_at_a = dy_dx.subs(x, a)
print(f"Độ dốc tại x = {a} : {gradient_at_a}")

Đạo hàm của y theo x: 30*x**5 + 20*x**3 + 9*x**2 + 5
Độ dốc tại x = 2 : 1161


In [33]:
import torch

# Bước 1: Tạo tensor với giá trị ban đầu là 2.0
x = torch.tensor(2.0, requires_grad=True)

# Bước 2: Định nghĩa hàm số y = x^3 + 2x^2 + 5x + 1
def y(x):
    return x**3 + 2*x**2 + 5*x + 1

# Bước 3: Đặt learning rate và số vòng lặp
learning_rate = 0.1
num_epochs = 10

# Bước 4: Thực hiện Gradient Descent
for epoch in range(num_epochs):
    # Tính giá trị của y
    y_value = y(x)

    # Tính gradient của y đối với x
    y_value.backward()

    # Cập nhật giá trị của x
    with torch.no_grad():
        x -= learning_rate * x.grad

    # Đặt lại gradient về 0 cho vòng lặp tiếp theo
    x.grad.zero_()

    # In giá trị của x và y sau mỗi vòng lặp
    print(f'Vòng lặp [{epoch + 1}/{num_epochs}], x: {x.item():.4f}, y: {y_value.item():.4f}')

# Kết quả cuối cùng
print(f'Giá trị cuối cùng của x: {x.item():.4f}')

Vòng lặp [1/10], x: -0.5000, y: 27.0000
Vòng lặp [2/10], x: -0.8750, y: -1.1250
Vòng lặp [3/10], x: -1.2547, y: -2.5137
Vòng lặp [4/10], x: -1.7251, y: -4.1001
Vòng lặp [5/10], x: -2.4278, y: -6.8073
Vòng lặp [6/10], x: -3.7250, y: -13.6609
Vòng lặp [7/10], x: -6.8977, y: -41.5604
Vòng lặp [8/10], x: -18.9120, y: -266.5102
Vòng lặp [9/10], x: -119.1464, y: -6142.3750
Vòng lặp [10/10], x: -4330.7476, y: -1663589.5000
Giá trị cuối cùng của x: -4330.7476


In [30]:
import torch
import numpy as np

# Bước 1: Tạo dữ liệu
torch.manual_seed(0)
x = torch.randint(1, 11, (100,), dtype=torch.float32).requires_grad_(True)
noise = torch.randn(100) * 0.5
y_true = 3 * x + 5 + noise

# Bước 2: Khởi tạo tham số
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Bước 3: Định nghĩa hàm MSE
def mse(y_true, y_pred):
    return ((y_true - y_pred) ** 2).mean()

# Bước 4: Lập trình Gradient Descent
learning_rate = 0.01
num_epochs = 100

for epoch in range(num_epochs):
    # Tính giá trị dự đoán
    y_pred = w * x + b

    # Tính MSE
    loss = mse(y_true, y_pred)

    # Tính gradient
    loss.backward(retain_graph=True)  # Retain the graph for the next backward pass

    # Cập nhật tham số
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    # Đặt lại gradient về 0 cho vòng lặp tiếp theo
    w.grad.zero_()
    b.grad.zero_()

    # In giá trị mất mát sau mỗi 10 vòng
    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}')

# Kết quả cuối cùng
print(f'Tham số cuối cùng: w = {w.item()}, b = {b.item()}')

Epoch [10/100], Loss: 5.2748
Epoch [20/100], Loss: 4.8557
Epoch [30/100], Loss: 4.4713
Epoch [40/100], Loss: 4.1186
Epoch [50/100], Loss: 3.7951
Epoch [60/100], Loss: 3.4984
Epoch [70/100], Loss: 3.2261
Epoch [80/100], Loss: 2.9764
Epoch [90/100], Loss: 2.7474
Epoch [100/100], Loss: 2.5373
Tham số cuối cùng: w = 3.4641854763031006, b = 1.6726096868515015


In [52]:
import torch
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)  # tensor([0, 1, 2, 3, 4])

arr[0] = 99
print(x)  # tensor([0, 1, 2, 3, 4])


# Tạo tensor rỗng với kích thước (2, 3)
x = torch.empty(2, 3)
print(x)
print("               ")
# Tạo tensor chứa toàn số 0 với kích thước (2, 3)
x = torch.zeros(2, 3)
print(x)
print("               ")
# Tạo tensor chứa toàn số 1 với kích thước (2, 3)
x = torch.ones(2, 3)
print(x)
print("               ")
# Tạo tensor với giá trị ngẫu nhiên từ phân phối đều trong khoảng [0, 1) với kích thước (2, 3)
x = torch.rand(2, 3)
print(x)
print("               ")
# Tạo tensor với kích thước (2, 3)
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("               ")
# Reshape tensor thành kích thước (3, 2) sử dụng view
y = x.view(3, 2)
print(y)
print("               ")
# Reshape tensor thành kích thước của tensor khác sử dụng view_as
z = torch.tensor([[1, 2], [3, 4], [5, 6]])
y = x.view_as(z)
print(y)


tensor([0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 4])
tensor([[3.2169e-32, 0.0000e+00, 1.0932e-32],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])
               
tensor([[0., 0., 0.],
        [0., 0., 0.]])
               
tensor([[1., 1., 1.],
        [1., 1., 1.]])
               
tensor([[0.2881, 0.6471, 0.6651],
        [0.8751, 0.3390, 0.5008]])
               
               
tensor([[1, 2],
        [3, 4],
        [5, 6]])
               
tensor([[1, 2],
        [3, 4],
        [5, 6]])
